In [12]:
import pandas as pd

df1 = pd.read_excel("./FakeRecogna.xlsx")
df2 = pd.read_excel("./FakeRecogna_no_removal_words.xlsx")

In [4]:
df1.head()

,Titulo,Subtitulo,Noticia,Categoria,Data,Autor,URL,Classe
0,\n\nPapa Francisco foi preso sob acusação de t...,Boato – Ocorreu um apagão no Vaticano. O papa ...,apagão vaticano papar presar acusação tráfico ...,entretenimento,11/01/2021,\nEdgard Matsuki,https://www.boatos.org/religiao/papa-francisco...,0.0
1,Equador prepara cova coletiva para mortos por ...,NaN,o governar equador anunciar preparar cova cole...,saúde,27/03/2020 18h25,27/03/2020 18h25,https://noticias.uol.com.br/internacional/ulti...,1.0
2,Air France voltará a operar voo direto Pequim-...,NaN,o companhia air france operar voar direto pequ...,saúde,07/08/2020 13h42,07/08/2020 13h42,https://www.uol.com.br/nossa/noticias/afp/2020...,1.0
3,Marfrig intensifica venda de carne do Brasil a...,NaN,o marfrig global foods retomar vender carnar b...,saúde,27/04/2020 14h53,27/04/2020 14h53,https://economia.uol.com.br/noticias/reuters/2...,1.0
4,As parciais das eleições de 2014 alternaram ma...,NaN,o assunto voltar o compartilhar rede social ju...,entretenimento,31/07/2021,Gilmar Lopes,https://www.e-farsas.com/as-parciais-das-eleic...,0.0

In [5]:
df2.head()

,Titulo,Subtitulo,Noticia,Categoria,Data,Autor,URL,Classe
0,\n\nArthur Lira fraudou a votação sobre voto i...,Boato – Está comprovado que a votação sobre o ...,bomba lira fraudar o votação brasília explodir...,política,17/08/2021,\nEdgard Matsuki,https://www.boatos.org/politica/arthur-lira-fr...,0
1,WhatsApp agora permite silenciar conversas e g...,"Opção vinha sendo testada no aplicativo, e foi...",o whatsapp liberar quinta-feira atualização ap...,política,23/10/2020 10h02,Por G1,https://g1.globo.com/economia/tecnologia/notic...,1
2,"Com Lula, Bolsonaro e Ciro, Fortaleza vira mic...",NaN,debater propor o cidade o campanha prefeitura ...,política,27/10/2020 04h00,Carlos Madeiro,https://noticias.uol.com.br/eleicoes/2020/10/2...,1
3,Alesp aprova projeto que multa em até R$ 100 m...,NaN,o alesp assembleia legislativo paulo aprovar h...,saúde,10/02/2021 23h56,10/02/2021 23h56,https://noticias.uol.com.br/saude/ultimas-noti...,1
4,\n Não é verdade que Fauci sabia há 15 anos q...,Publicações compartilhadas dezenas de vezes de...,“ fauci aprovar o hidroxicloroquina haver ano ...,saúde,11/08/2020 às 20:45,AFP Austrália,https://checamos.afp.com//nao-e-verdade-que-fa...,0

In [20]:
df1.info()

<class 'pandas.DataFrame'>
Index: 11872 entries, 0 to 11902
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Titulo     11872 non-null  str
 1   Subtitulo  5580 non-null   str
 2   Noticia    11872 non-null  str
 3   Categoria  11872 non-null  str
 4   Data       11521 non-null  object
 5   Autor      11856 non-null  str
 6   URL        11872 non-null  str
 7   Classe     11872 non-null  float64
dtypes: float64(1), object(1), str(6)
memory usage: 11.4+ MB

In [19]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 11902 entries, 0 to 11901
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Titulo     11872 non-null  str
 1   Subtitulo  5580 non-null   str
 2   Noticia    11902 non-null  str
 3   Categoria  11902 non-null  str
 4   Data       11551 non-null  object
 5   Autor      11886 non-null  str
 6   URL        11902 non-null  str
 7   Classe     11902 non-null  int64
dtypes: int64(1), object(1), str(6)
memory usage: 11.2+ MB

In [ ]:
# Remover todas as linhas que não tiverem título
df1 = df1.dropna(subset=['Titulo'])

df1.info()

<class 'pandas.DataFrame'>
Index: 11872 entries, 0 to 11902
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Titulo     11872 non-null  str
 1   Subtitulo  5580 non-null   str
 2   Noticia    11872 non-null  str
 3   Categoria  11872 non-null  str
 4   Data       11521 non-null  object
 5   Autor      11856 non-null  str
 6   URL        11872 non-null  str
 7   Classe     11872 non-null  float64
dtypes: float64(1), object(1), str(6)
memory usage: 11.4+ MB

In [21]:
df2 = df2.dropna(subset=['Titulo'])

df2.info()

<class 'pandas.DataFrame'>
Index: 11872 entries, 0 to 11901
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Titulo     11872 non-null  str
 1   Subtitulo  5580 non-null   str
 2   Noticia    11872 non-null  str
 3   Categoria  11872 non-null  str
 4   Data       11521 non-null  object
 5   Autor      11856 non-null  str
 6   URL        11872 non-null  str
 7   Classe     11872 non-null  int64
dtypes: int64(1), object(1), str(6)
memory usage: 11.2+ MB

In [14]:
# Vamos identificar o que tem na coluna "Classe"
df1['Classe'].unique()

array([0., 1.])

In [16]:
# Vamos transformar a coluna "Classe" em uma coluna de inteiros.
df1_int = df1.copy()
df1_int['Classe'] = df1['Classe'].astype(int)

df1_int.info()

<class 'pandas.DataFrame'>
Index: 11872 entries, 0 to 11902
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Titulo     11872 non-null  str
 1   Subtitulo  5580 non-null   str
 2   Noticia    11872 non-null  str
 3   Categoria  11872 non-null  str
 4   Data       11521 non-null  object
 5   Autor      11856 non-null  str
 6   URL        11872 non-null  str
 7   Classe     11872 non-null  int64
dtypes: int64(1), object(1), str(6)
memory usage: 11.4+ MB

In [18]:
df1_int['Classe'].unique()

array([0, 1])

In [22]:
# Salvando os dataframes
df1_int.to_csv("./FakeRecogna_tratada.csv", index=False)
df2.to_csv("./FakeRecogna_no_removal_words_tratada.csv", index=False)